/**
 * seeders/seed.js
 * Run with:  node seeders/seed.js
 * Inserts 90 realistic Blinkit-style products into the `products` table.
 * Safe to run multiple times — clears existing products first.
 */
import "dotenv/config";
import sequelize from "../config/db.js";
import Product   from "../models/Product.js";

const NOW = new Date().toISOString().slice(0, 19).replace("T", " ");

const products = [
  // ── Fruits & Vegetables (12) ─────────────────────────────────────────────
  { name: "Fresh Tomatoes", description: "Farm-fresh red tomatoes, perfect for curries, salads, and chutneys. Handpicked daily.", price: 35.00, stock: 200, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/533280/pexels-photo-533280.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Baby Spinach", description: "Tender washed baby spinach leaves. Rich in iron, folate, and vitamins A and C.", price: 49.00, stock: 150, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/2325843/pexels-photo-2325843.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Bananas", description: "Sweet Cavendish bananas. Great source of potassium and natural energy. Pack of 6.", price: 55.00, stock: 300, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/1093038/pexels-photo-1093038.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Red Onions", description: "Premium quality red onions — a kitchen essential for every Indian household. 1 kg pack.", price: 39.00, stock: 400, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/4197447/pexels-photo-4197447.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Shimla Apples", description: "Crisp and sweet apples from the orchards of Himachal Pradesh. Pack of 4 large apples.", price: 149.00, stock: 120, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/1510392/pexels-photo-1510392.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Potatoes", description: "Farm-fresh white potatoes. Versatile for sabji, fry, or soup. 1 kg net weight.", price: 45.00, stock: 500, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/144248/potatoes-vegetables-erdfrucht-bio-144248.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Carrots", description: "Crunchy orange carrots loaded with beta-carotene. Great for juices and halwa. 500 g pack.", price: 42.00, stock: 180, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/1306559/pexels-photo-1306559.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Green Capsicum", description: "Fresh green bell peppers with a mild, crisp flavour. Perfect for stir-fries and pizzas.", price: 55.00, stock: 160, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/1435904/pexels-photo-1435904.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Cauliflower", description: "White, firm cauliflower head sourced from local farms. Ideal for aloo gobi and soups.", price: 65.00, stock: 100, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/461428/pexels-photo-461428.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Mangoes (Alphonso)", description: "King of fruits — luscious Alphonso mangoes from Ratnagiri. Seasonal, limited stock. 3 pcs.", price: 199.00, stock: 80, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/2363345/pexels-photo-2363345.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Cucumber", description: "Cool and refreshing cucumbers. Ideal for salads, raita, and detox water. 500 g pack.", price: 30.00, stock: 250, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/37528/cucumber-salad-food-healthy-37528.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Sweet Corn (2 pcs)", description: "Fresh tender sweet corn. Ready to boil or grill. Great as a healthy evening snack.", price: 45.00, stock: 130, category: "Fruits & Vegetables", image: "https://images.pexels.com/photos/547263/pexels-photo-547263.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  // ── Dairy & Breakfast (10) ────────────────────────────────────────────────
  { name: "Amul Taaza Milk 500ml", description: "Amul Taaza toned milk — pasteurized and homogenized for everyday use. 500 ml pouch.", price: 28.00, stock: 600, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Amul Gold Full Cream Milk", description: "Rich full-cream milk with high fat content. Ideal for tea, coffee, and desserts. 500 ml.", price: 32.00, stock: 400, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/414262/pexels-photo-414262.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Farm Fresh Eggs (12 pcs)", description: "Protein-rich white eggs from cage-free farms. Perfect for your daily breakfast. 12-pack.", price: 89.00, stock: 350, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/162712/egg-white-food-protein-162712.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Amul Butter 100g", description: "Amul pasteurised salted butter. India's favourite butter for bread, rotis, and cooking.", price: 55.00, stock: 300, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/531334/pexels-photo-531334.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Greek Yogurt 400g", description: "Thick, creamy Greek yogurt — high in protein and probiotics. Flavoured with real fruit.", price: 99.00, stock: 150, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/1435735/pexels-photo-1435735.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Amul Cheese Slices 200g", description: "Processed cheese slices — great for sandwiches, burgers, and pasta. 10 slices per pack.", price: 115.00, stock: 200, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/821365/pexels-photo-821365.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Bagrry's Oats 1kg", description: "Heart-healthy rolled oats. Cooks in 3 minutes. High in fibre and beta-glucan.", price: 145.00, stock: 180, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/216951/pexels-photo-216951.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Kellogg's Corn Flakes 500g", description: "Classic crunchy corn flakes made with sun-ripened corn. A wholesome start to your morning.", price: 175.00, stock: 220, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/1359326/pexels-photo-1359326.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Kissan Mixed Fruit Jam 500g", description: "Fruity, sweet mixed fruit jam made with real fruits. Perfect on toast, parathas, and pancakes.", price: 125.00, stock: 160, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/3338492/pexels-photo-3338492.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Britannia Bread (White) 400g", description: "Soft, fresh white sandwich bread. Made with enriched wheat flour. Stay fresh for 5 days.", price: 42.00, stock: 280, category: "Dairy & Breakfast", image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  // ── Snacks & Munchies (10) ────────────────────────────────────────────────
  { name: "Lay's Classic Salted 73g", description: "Crispy potato chips with the perfect amount of salt. America's favourite snack, now in India.", price: 20.00, stock: 500, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/1893556/pexels-photo-1893556.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Kurkure Masala Munch 90g", description: "India's favourite crunchy corn snack with a spicy masala twist. Irresistibly puffed.", price: 20.00, stock: 450, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/2228553/pexels-photo-2228553.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Lay's Magic Masala 52g", description: "Tangy, spicy Lay's chips in the classic Magic Masala flavour. A bestselling Indian flavour.", price: 20.00, stock: 480, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/1093491/pexels-photo-1093491.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Haldiram's Aloo Bhujia 200g", description: "Authentic Rajasthani aloo bhujia made with potatoes and aromatic spices. Zero trans fat.", price: 65.00, stock: 300, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/3762069/pexels-photo-3762069.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Pringles Original 107g", description: "Perfectly stackable, uniformly shaped potato crisps in the iconic Pringles can. Original flavour.", price: 149.00, stock: 200, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Bingo Mad Angles 55g", description: "Triangular corn chips with a zesty chilli-lime flavour. Crunchy snack for all ages.", price: 20.00, stock: 350, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/1893555/pexels-photo-1893555.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Doritos Nacho Cheese 130g", description: "Boldly flavoured tortilla chips with real cheese coating. The perfect party snack.", price: 120.00, stock: 180, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/2611917/pexels-photo-2611917.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Maggi 2-Minute Noodles 70g", description: "India's iconic 2-minute masala noodles. Quick, tasty, and loved by millions.", price: 14.00, stock: 800, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/2347311/pexels-photo-2347311.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Sunfeast Dark Fantasy 150g", description: "Indulgent dark chocolate cream-filled biscuits. A luxurious treat for chocolate lovers.", price: 60.00, stock: 250, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/918327/pexels-photo-918327.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Parle-G Biscuits 800g", description: "India's most loved glucose biscuit for over 80 years. Great with chai, anytime.", price: 85.00, stock: 600, category: "Snacks & Munchies", image: "https://images.pexels.com/photos/890515/pexels-photo-890515.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  // ── Cold Drinks & Juices (9) ──────────────────────────────────────────────
  { name: "Coca-Cola 750ml", description: "The original and iconic Coca-Cola. Refreshing carbonated cola for every occasion.", price: 45.00, stock: 400, category: "Cold Drinks & Juices", image: "https://images.pexels.com/photos/3727250/pexels-photo-3727250.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Pepsi 750ml", description: "Bold, refreshing cola with a crisp, clean taste. Chill and enjoy with food or solo.", price: 45.00, stock: 380, category: "Cold Drinks & Juices", image: "https://images.pexels.com/photos/2983100/pexels-photo-2983100.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Sprite 750ml", description: "Crisp, clean lemon-lime flavoured carbonated drink. No caffeine. Perfectly refreshing.", price: 45.00, stock: 350, category: "Cold Drinks & Juices", image: "https://images.pexels.com/photos/1292294/pexels-photo-1292294.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Real Fruit Juice — Mixed Fruit 1L", description: "100% real mixed fruit juice with no added preservatives. A refreshing glass of goodness.", price: 99.00, stock: 220, category: "Cold Drinks & Juices", image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Tropicana Orange Juice 1L", description: "Chilled, fresh-tasting orange juice made from handpicked oranges. 100% fruit, no sugar added.", price: 110.00, stock: 200, category: "Cold Drinks & Juices", image: "https://images.pexels.com/photos/158053/fresh-orange-juice-squeezed-158053.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Red Bull Energy Drink 250ml", description: "Gives you wings. Red Bull energy drink with caffeine, B-vitamins, and taurine. 250 ml can.", price: 125.00, stock: 250, category: "Cold Drinks & Juices", image: "https://images.pexels.com/photos/3407777/pexels-photo-3407777.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "B Natural Lychee Drink 180ml", description: "Sweet and fragrant lychee fruit drink made with real fruit pulp. No artificial colours.", price: 20.00, stock: 300, category: "Cold Drinks & Juices", image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Maaza Mango 600ml", description: "Thick, sweet mango drink with the taste of real Alphonso mango pulp. Chilled to perfection.", price: 35.00, stock: 320, category: "Cold Drinks & Juices", image: "https://images.pexels.com/photos/2115257/pexels-photo-2115257.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Limca 750ml", description: "Zingy lemon and lime flavoured sparkling drink. Refreshes you from within.", price: 40.00, stock: 280, category: "Cold Drinks & Juices", image: "https://images.pexels.com/photos/1638280/pexels-photo-1638280.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  // ── Tea & Coffee (8) ─────────────────────────────────────────────────────
  { name: "Nescafe Classic 50g", description: "Nescafe Classic instant coffee — bold, rich flavour with a smooth, satisfying aroma.", price: 149.00, stock: 250, category: "Tea & Coffee", image: "https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Tata Tea Premium 500g", description: "Strong, aromatic tea from India's most trusted brand. Blended for a full-bodied cup.", price: 210.00, stock: 300, category: "Tea & Coffee", image: "https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Red Label Tea 500g", description: "Brooke Bond Red Label — the taste of togetherness. Premium tea for a strong, refreshing brew.", price: 225.00, stock: 280, category: "Tea & Coffee", image: "https://images.pexels.com/photos/1793035/pexels-photo-1793035.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Bru Instant Coffee 200g", description: "South India's favourite coffee blend with the perfect mix of coffee and chicory.", price: 210.00, stock: 200, category: "Tea & Coffee", image: "https://images.pexels.com/photos/374757/pexels-photo-374757.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Tetley Green Tea 25 bags", description: "Light and refreshing green tea with natural antioxidants. Supports immunity and wellness.", price: 99.00, stock: 220, category: "Tea & Coffee", image: "https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Nescafe Gold Blend 50g", description: "Premium Arabica and Robusta blend for a rich, smooth coffee experience at home.", price: 299.00, stock: 150, category: "Tea & Coffee", image: "https://images.pexels.com/photos/373639/pexels-photo-373639.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Vedaka Green Tea 100 bags", description: "Refreshing green tea bags at an everyday price. Packed with natural antioxidants.", price: 149.00, stock: 180, category: "Tea & Coffee", image: "https://images.pexels.com/photos/1417945/pexels-photo-1417945.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Starbucks VIA Instant Coffee 8 pcs", description: "Café-quality Starbucks coffee in an instant. Premium Colombian medium-roast blend.", price: 399.00, stock: 100, category: "Tea & Coffee", image: "https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  // ── Bakery & Biscuits (8) ─────────────────────────────────────────────────
  { name: "Britannia Good Day Butter 150g", description: "Rich buttery cookies with a melt-in-your-mouth texture. Perfect with tea or coffee.", price: 30.00, stock: 350, category: "Bakery & Biscuits", image: "https://images.pexels.com/photos/890515/pexels-photo-890515.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Hide & Seek Choco Chips 100g", description: "Chocolate chip cookies with real chocolate chips baked in. A childhood favourite.", price: 35.00, stock: 300, category: "Bakery & Biscuits", image: "https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Oreo Original 120g", description: "The classic twist-lick-dunk sandwich cookie with creamy vanilla filling. 16 cookies per pack.", price: 45.00, stock: 400, category: "Bakery & Biscuits", image: "https://images.pexels.com/photos/890515/pexels-photo-890515.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Marie Gold Biscuits 250g", description: "Light and crispy Marie biscuits — perfect for dunking in tea. A classic Indian biscuit.", price: 25.00, stock: 450, category: "Bakery & Biscuits", image: "https://images.pexels.com/photos/221012/pexels-photo-221012.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Nutella 200g", description: "Ferrero Nutella — hazelnut spread with cocoa. A delicious start to every morning.", price: 179.00, stock: 200, category: "Bakery & Biscuits", image: "https://images.pexels.com/photos/918327/pexels-photo-918327.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Britannia 50-50 Maska Chaska 200g", description: "Flaky, buttery crackers with a light salty-sweet balance. Great as a snack or with chai.", price: 30.00, stock: 320, category: "Bakery & Biscuits", image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Bonn Garlic Bread 150g", description: "Soft, herby garlic bread rolls ready to heat and eat. Perfect with pasta and soups.", price: 55.00, stock: 150, category: "Bakery & Biscuits", image: "https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "McVitie's Digestive Biscuits 400g", description: "Wholegrain wheat digestive biscuits. High in fibre. A classic British biscuit now in India.", price: 120.00, stock: 180, category: "Bakery & Biscuits", image: "https://images.pexels.com/photos/230325/pexels-photo-230325.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  // ── Atta, Rice & Dal (9) ─────────────────────────────────────────────────
  { name: "Aashirvaad Atta 5kg", description: "100% whole wheat atta with natural bran and germ. Makes soft, nutritious rotis.", price: 289.00, stock: 200, category: "Atta, Rice & Dal", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "India Gate Basmati Rice 5kg", description: "Premium extra-long grain Basmati rice. Aromatic, fluffy, and perfect for biryani and pulao.", price: 545.00, stock: 150, category: "Atta, Rice & Dal", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Toor Dal (Split Pigeon Peas) 1kg", description: "Premium quality toor dal for everyday cooking. Rich in protein and easy to digest.", price: 155.00, stock: 250, category: "Atta, Rice & Dal", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Moong Dal (Yellow Split) 500g", description: "Washed yellow moong dal — ideal for khichdi, dal tadka, and halwa. Cooks quickly.", price: 89.00, stock: 220, category: "Atta, Rice & Dal", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Chana Dal 1kg", description: "Hulled and split Bengal gram. High in protein and fibre. Great for dal, chaat, and snacks.", price: 99.00, stock: 200, category: "Atta, Rice & Dal", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Rajma (Kidney Beans) 500g", description: "Dark red kidney beans for the classic rajma curry. Soak overnight for best results.", price: 75.00, stock: 180, category: "Atta, Rice & Dal", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Sona Masoori Rice 5kg", description: "Light, low-calorie South Indian variety. Ideal for daily meals, idli, and dosa batter.", price: 299.00, stock: 160, category: "Atta, Rice & Dal", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Besan (Chickpea Flour) 500g", description: "Fine quality gram flour for pakoras, kadhi, and sweets. Gluten-free and protein-rich.", price: 65.00, stock: 280, category: "Atta, Rice & Dal", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Maida (All Purpose Flour) 1kg", description: "Fine refined wheat flour for breads, naan, puri, and baking. Smooth and consistent.", price: 45.00, stock: 300, category: "Atta, Rice & Dal", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  // ── Masala & Oils (9) ────────────────────────────────────────────────────
  { name: "Fortune Sunflower Oil 1L", description: "Refined sunflower oil with Vitamins A, D, and E. Light on the stomach, great for frying.", price: 155.00, stock: 250, category: "Masala & Oils", image: "https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking.jpg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Saffola Gold Oil 1L", description: "Blended rice bran and sunflower oil. Rich in antioxidants. Promotes heart health.", price: 179.00, stock: 200, category: "Masala & Oils", image: "https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking.jpg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "MDH Garam Masala 100g", description: "Aromatic blend of whole spices. Adds depth and warmth to curries, rice, and gravies.", price: 85.00, stock: 300, category: "Masala & Oils", image: "https://images.pexels.com/photos/2802527/pexels-photo-2802527.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Everest Rajwadi Garam Masala 100g", description: "Premium Rajasthani blend of over 15 spices. Rich, bold flavour for authentic Indian cooking.", price: 90.00, stock: 250, category: "Masala & Oils", image: "https://images.pexels.com/photos/2802527/pexels-photo-2802527.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Tata Salt 1kg", description: "India's most trusted iodised salt. Free-flowing and pure. Essential for every kitchen.", price: 28.00, stock: 500, category: "Masala & Oils", image: "https://images.pexels.com/photos/4110251/pexels-photo-4110251.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Catch Turmeric Powder 200g", description: "Vibrant yellow turmeric powder with high curcumin content. Essential for Indian cooking.", price: 55.00, stock: 350, category: "Masala & Oils", image: "https://images.pexels.com/photos/2802527/pexels-photo-2802527.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "MDH Chhole Masala 100g", description: "Perfect spice blend for authentic Punjabi chole. Makes restaurant-style chickpea curry at home.", price: 75.00, stock: 280, category: "Masala & Oils", image: "https://images.pexels.com/photos/2802527/pexels-photo-2802527.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Saffola Olive Oil 500ml", description: "Extra virgin olive oil cold pressed from the finest olives. Great for salads and low-heat cooking.", price: 449.00, stock: 120, category: "Masala & Oils", image: "https://images.pexels.com/photos/33783/olive-oil-salad-dressing-cooking.jpg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Organic India Amla Powder 100g", description: "Pure amla (Indian gooseberry) powder. Rich in Vitamin C. Great for immunity and hair health.", price: 120.00, stock: 150, category: "Masala & Oils", image: "https://images.pexels.com/photos/2802527/pexels-photo-2802527.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  // ── Personal Care (10) ────────────────────────────────────────────────────
  { name: "Dove Body Wash 190ml", description: "Dove Deeply Nourishing body wash. Leaves skin soft, smooth, and moisturised for 24 hours.", price: 199.00, stock: 200, category: "Personal Care", image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Head & Shoulders Shampoo 340ml", description: "Anti-dandruff shampoo with ZPT formula. Removes dandruff from first wash and keeps scalp clean.", price: 279.00, stock: 180, category: "Personal Care", image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Colgate MaxFresh Toothpaste 150g", description: "Spearmint gel toothpaste with micro-granules. Provides 12-hour fresh breath protection.", price: 115.00, stock: 350, category: "Personal Care", image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Gillette Mach3 Razor", description: "Triple-blade shaving razor with anti-friction blades. Provides a close, comfortable shave.", price: 249.00, stock: 150, category: "Personal Care", image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Nivea Men Face Wash 100ml", description: "Deep cleaning face wash for men. Removes oil and dirt without drying out the skin.", price: 149.00, stock: 180, category: "Personal Care", image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Whisper Ultra 40 Pads", description: "Whisper Ultra thin sanitary pads with wings. Provides up to 8 hours of leak-free protection.", price: 199.00, stock: 250, category: "Personal Care", image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Pampers Baby Diapers S 20 pcs", description: "Pampers Active Baby dry diapers for 4–8 kg babies. Keeps baby dry for up to 12 hours.", price: 349.00, stock: 180, category: "Personal Care", image: "https://images.pexels.com/photos/35537/child-children-girl-happy.jpg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Neutrogena Moisturiser SPF15 50ml", description: "Lightweight daily moisturiser with SPF15. Non-greasy formula for normal to oily skin.", price: 349.00, stock: 120, category: "Personal Care", image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Wild Stone Deo Spray 150ml", description: "Long-lasting deodorant with a fresh masculine fragrance. Controls body odour for 24 hours.", price: 199.00, stock: 200, category: "Personal Care", image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Listerine Cool Mint Mouthwash 250ml", description: "Antiseptic mouthwash kills 99.9% germs. Provides 12-hour fresh breath. Alcohol-free formula.", price: 139.00, stock: 160, category: "Personal Care", image: "https://images.pexels.com/photos/3735657/pexels-photo-3735657.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  // ── Household Essentials (10) ─────────────────────────────────────────────
  { name: "Surf Excel Matic Powder 1kg", description: "Front-load washing machine detergent. Superior stain removal even in cold water.", price: 215.00, stock: 200, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Vim Dishwash Bar 200g", description: "Lemon-scented dish wash bar. Cuts through grease effortlessly. Leaves dishes sparkling.", price: 25.00, stock: 400, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Colin Glass Cleaner 500ml", description: "Streak-free glass cleaning spray. Cleans windows, mirrors, and glass surfaces in seconds.", price: 135.00, stock: 180, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Lizol Floor Cleaner 500ml", description: "Disinfectant floor cleaner that kills 99.9% germs. Leaves a long-lasting fresh fragrance.", price: 149.00, stock: 200, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Good Knight Mosquito Repellent Liquid", description: "Fast-acting mosquito repellent liquid refill. Provides all-night protection for 45 nights.", price: 89.00, stock: 250, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Harpic Power Plus 500ml", description: "Powerful toilet cleaner with 10× cleaning action. Kills 99.9% germs and removes tough stains.", price: 125.00, stock: 200, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Glad Zipper Freezer Bags 15 pcs", description: "Double-zip seal freezer bags for food storage. Keeps food fresh longer. Microwave safe.", price: 199.00, stock: 150, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Ariel Matic Liquid 500ml", description: "Liquid detergent designed for fully automatic washing machines. Removes tough stains effortlessly.", price: 255.00, stock: 180, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Scotch-Brite Scrub Pad 3 pcs", description: "Heavy-duty scrubbing pads for pots and pans. Removes burnt food without scratching.", price: 55.00, stock: 300, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
  { name: "Pril Dishwash Gel 500ml", description: "Active lime dishwashing gel. Cuts through grease on the first drop. Long-lasting lather.", price: 119.00, stock: 220, category: "Household Essentials", image: "https://images.pexels.com/photos/4239037/pexels-photo-4239037.jpeg?auto=compress&cs=tinysrgb&w=400", isAvailable: true },
];

// ─── Runner ───────────────────────────────────────────────────────────────────
const seed = async () => {
  try {
    await sequelize.authenticate();
    console.log("✅ Connected to database.");

    // Sync the Product table (creates it if missing, alters if schema changed)
    await Product.sync({ alter: true });

    // Disable FK checks so we can delete products even when cart_items references them
    await sequelize.query("SET FOREIGN_KEY_CHECKS = 0");
    await Product.destroy({ where: {}, truncate: true });
    await sequelize.query("SET FOREIGN_KEY_CHECKS = 1");
    console.log("🗑️  Cleared existing products.");

    // Bulk-insert all products
    const inserted = await Product.bulkCreate(products, { validate: true });
    console.log(`✅ Seeded ${inserted.length} products successfully.`);

    // Summary by category
    const summary = products.reduce((acc, p) => {
      acc[p.category] = (acc[p.category] || 0) + 1;
      return acc;
    }, {});
    console.log("\n📦 Products per category:");
    Object.entries(summary).forEach(([cat, count]) =>
      console.log(`   ${cat.padEnd(30)} ${count}`)
    );

    process.exit(0);
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
    console.error(error);
    process.exit(1);
  }
};

seed();
